### ISSUE TITLE
Android pthread_cancel()

### ISSUE THREAD

**Issue by Achder** [LancePutnam/Gamma#46]
Can't compile the library, because Android doesn't support pthread_cancel().
Is there a workaround for this?

**Comment by LancePutnam** [comment]
Not that I know of. Thread cancellation seems to be considered bad practice these days (e.g. no support under std::thread) since it can lead to resource leaks. See http://stackoverflow.com/questions/13893060/i-want-to-kill-a-stdthread-using-its-thread-object

For this reason and the fact that Thread::cancel is not used internally by Gamma, I have removed it.
